language: generic
before_deploy:
  - "cd 1.12 && zip -r pack.zip ."
  - "cd ../1.13+ && zip -r pack.zip ."
  - "cd ../"
  - "cp 1.12/pack.zip DiscoveryNetwork_RP_1_12-$TRAVIS_BRANCH-$TRAVIS_BUILD_ID.zip"
  - "cp 1.13+/pack.zip DiscoveryNetwork_RP_1_13-$TRAVIS_BRANCH-$TRAVIS_BUILD_ID.zip"
deploy:
  provider: releases
  skip_cleanup: true
  tag_name: $TRAVIS_BRANCH-$TRAVIS_BUILD_ID
  body: $TRAVIS_COMMIT_MESSAGE
  api_key: $GH_TOKEN
  on:
    all_branches: true
    tags: false
  file_glob: true
  file: "*.zip"