name: Create Release
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Zip folder
        run: zip -r discov-resourcepack-main-${{ github.run_id }}.zip . -x ".github/*" ".git/*"

      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref_name }}-${{ github.run_id }}
          tag_name: ${{ github.ref_name }}-${{ github.run_id }}
          body_path: CHANGELOG.md
          
      - name: Add artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: discov-resourcepack-main-${{ github.run_id }}.zip
          asset_name: discov-resourcepack-main-${{ github.run_id }}.zip
          asset_content_type: application/zip
